version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: steamstats
      POSTGRES_USER: steam
      POSTGRES_PASSWORD: steam
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U steam -d steamstats"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://steam:steam@db:5432/steamstats
      - PORT=3001
    depends_on:
      db:
        condition: service_healthy 